### ISSUE TITLE
MIT or Apache 2.0 license?

### ISSUE THREAD

**Issue by smoelius** [d-e-s-o/test-env-log#1]
Would you consider relaxing the license from "GPL-3.0-or-later" to "MIT OR Apache-2.0"?

This would be consistent with much of the larger Rust universe, and could make your crate suitable for use in projects where it otherwise would not be.

**Comment by d-e-s-o** [comment]
Yes, I will change it.

**Comment by smoelius** [comment]
Thanks!

**Comment by d-e-s-o** [comment]
Done (https://github.com/d-e-s-o/test-env-log/commit/5e224ed38f6df6a58a8153f0db4cbcbcf92b2866). Pushed new release, `0.2.1`.

**Comment by smoelius** [comment]
Thanks again. :)
