### ISSUE TITLE
Support logging tracing span enter/exit

### ISSUE THREAD

**Issue by danielzfranklin** [d-e-s-o/test-env-log#10]
I would find it useful to get a msg when we enter/exit a span. Would you accept a PR that logs this info when under the feature `trace`?

**Comment by d-e-s-o** [comment]
Can you elaborate a bit, please? Shouldn't this be up to the code under test?

**Comment by danielzfranklin** [comment]
Nevermind, I think this is already possible. I didn't understand env_logger

**Comment by danielzfranklin** [comment]
Actually a change is needed to this library to allow users to log span events.

Suppose a user asks for trace events with `RUST_LOG=trace`.

With this change we get span events that look like this:

```
Mar 21 18:48:48.417  INFO open{self=DeviceNode { id: 2 }}: evdi::device_node: new
Mar 21 18:48:48.418  INFO open{self=DeviceNode { id: 2 }}: evdi::device_node: enter
Mar 21 18:48:48.418  INFO open{self=DeviceNode { id: 2 }}:status{self=DeviceNode { id: 2 }}: evdi::device_node: new
Mar 21 18:48:48.418  INFO open{self=DeviceNode { id: 2 }}:status{self=DeviceNode { id: 2 }}: evdi::device_node: enter
Mar 21 18:48:48.418  INFO open{self=DeviceNode { id: 2 }}:status{self=DeviceNode { id: 2 }}: evdi::device_node: exit
Mar 21 18:48:48.418  INFO open{self=DeviceNode { id: 2 }}:status{self=DeviceNode { id: 2 }}: evdi::device_node: close time.busy=73.4µs time.idle=113µs
Mar 21 18:48:48.422  INFO open{self=DeviceNode { id: 2 }}: evdi::device_node: exit
Mar 21 18:48:48.422  INFO open{self=DeviceNode { id: 2 }}: evdi::device_node: close time.busy=4.22ms time.idle=122µs
```

Without this change they would get the current span context as part of the log lines for events, but not span events.
```diff
         let subscriber = ::tracing_subscriber::FmtSubscriber::builder()
+            .with_span_events(tracing_subscriber::fmt::format::FmtSpan::FULL)
             .with_env_filter(::tracing_subscriber::EnvFilter::from_default_env())
             .finish();
```

I'm not sure if the filter should be FULL, or if this should be configurable.

**Comment by d-e-s-o** [comment]
Hm, interesting. I wasn't even aware of this functionality. Seems to be purely a policy decision. That being said, I am not opposed to it on the grounds that `#[test]` is meant for reasonably small tests and there having a bit more information is presumably helpful and not generating too much noise. Also, the timing information seems nice. I agree that ideally that would be configurable, but I am not sure there is a good way to go about that. So what you propose seems like a sensible default.

**Comment by danielzfranklin** [comment]
This feels a little hacky, but it might be nice to read the filter from an environment variable. Playing around with this in a fork, I've found myself wanting different filters when debugging different sorts of issues.
