### ISSUE TITLE
Allow custom subscribers with the internal subscriber as a default/fallback

### ISSUE THREAD

**Issue by seanpianka** [d-e-s-o/test-env-log#14]
* **What is the current behavior?**

Tests decorated with `traced_test` use the internal subscriber implementation found [here](url).

* **What is the expected behavior?**

Tests can specify a subscriber implementation to use for the tests.

* **What is the motivation / use case for changing the behavior?**

Users can specify custom subscribers for a variety of reasons. One thought is to support a similar subscriber that [tracing-test](https://github.com/dbrgn/tracing-test) provides:

> The macro provided in this crate registers a global default subscriber instead. This subscriber contains a writer which logs into a global static in-memory buffer.

**Comment by d-e-s-o** [comment]
Hm, there is no `traced_test` attribute provided by this crate and the first link is dead.

**Comment by d-e-s-o** [comment]
So if I understand what you are asking correctly, how do you envision a user changing the subscriber?

**Comment by d-e-s-o** [comment]
Given the lack of responses I assume this is no longer a desired feature.

**Comment by teohhanhui** [comment]
> I assume this is no longer a desired feature

It's most definitely a desirable feature. I'd love to be able to use something like https://github.com/kolloch/reqray
