### ISSUE TITLE
Requires env-logger

### ISSUE THREAD

**Issue by eloff** [d-e-s-o/test-env-log#15]
I get the error:

```
error[E0433]: failed to resolve: could not find `env_logger` in the list of imported crates
  --> src/tests/backend_auth_test.rs:10:1
   |
10 | #[test(tokio::test)]
   | ^^^^^^^^^^^^^^^^^^^^ could not find `env_logger` in the list of imported crates
```

Which goes away when I add env_logger to *my* dev-dependencies. I think it probably should be a dependency, not a dev-dependency for this crate.

**Comment by d-e-s-o** [comment]
Unfortunately, that's not how it works, see: https://github.com/d-e-s-o/test-env-log/commit/db6e7001cf260b8c7115c11a19ce0834cd62806d.

**Comment by d-e-s-o** [comment]
I assume the above answers the question.

**Comment by azdle** [comment]
> From the looks of it, proc-macro crates' dependencies are treated a bit
> differently by Cargo than those of library crates. In particular, they
> are not "inherited" by (and, hence, available in) the consuming crate.
> As such, the dependency to env_logger that we had specified all along
> was effectively unused: while we emitted code that requires the
> dependency to be available, it still had to be specified explicitly in
> the crate making use of test-env-log.
> This change fixes the confusion by converting the dependency to a
> dev-only one. We require still require it for testing because our tests
> execute the emitted code.

Hey, @d-e-s-o. Apologies if you're already aware of this. If you wanted to make this work, you just need to structure this as two different crates. If you moved the current macro crate into a `test-log-macros` and then just `pub use` each macro from a new standard `test-log` crate. Then you could have `env_log` (and/or `tracing-subcriber`) as a dependency of the top-level `test-log` and have it actually get propagated up.

**Comment by d-e-s-o** [comment]
Ah interesting. Yeah, I didn't think of that -- may be worthwhile to pursue.

**Comment by d-e-s-o** [comment]
The one downside I see is that at least when using resolver v2 (the default), users would no longer be able to enable additional features of `tracing`/`tracing-subscriber`. Colored output, for example, should be configurable this way. On the bright side, we could facade it properly then behind a `colored` feature that applies to both `log` and `tracing`.

**Comment by azdle** [comment]
Maybe there's some nuance in the v2 resolver that I'm not aware of, but based on rereading [the section of the book](https://doc.rust-lang.org/cargo/reference/resolver.html#features) it sounds like dev-dependencies' features are still unified if the dev-dependencies are used, so a parallel dev-dependency with added features should still work. 

Or, maybe I'm misinterpreting what you meant would be a problem?

But, reguarless a `test-log` feature would still be an even nicer option if you like that.

**Comment by d-e-s-o** [comment]
Ah indeed; just tried it out, it would still work. Glad we discussed that ;)

**Comment by Stargateur** [comment]
It would be nice to reopen this issue
