### ISSUE TITLE
RUST_LOG_SPAN_EVENTS=none

### ISSUE THREAD

**Issue by janimo** [d-e-s-o/test-env-log#16]
It would be convenient to be able to disable logging spans by toggling to none, not just by omitting to set the variable.

**Comment by d-e-s-o** [comment]
Hm, we could do that. But I think it's inconsistent with respect to `RUST_LOG`, which I don't *believe* supports such a setting (but is also [indirectly] honored by this crate).

**Comment by janimo** [comment]
RUST_LOG supports the the pseudo-logging level 'off'.

**Comment by d-e-s-o** [comment]
Awesome! I suspect we could do the same for `RUST_LOG_SPAN_EVENTS`. Would that work for you?

**Comment by janimo** [comment]
Sure. I was thinking of none because of FmtSpan::NONE there, but off works just fine I guess :)

**Comment by d-e-s-o** [comment]
I think a consistent user experience should supersede some implementation detail. In any event, feel free to open a pull request if you have cycles to look into it. I am not sure when I will get to it.
