### ISSUE TITLE
Support tracing-error

### ISSUE THREAD

**Issue by samoylovfp** [d-e-s-o/test-env-log#2]
tracing-error crate requires more setup to work
https://github.com/tokio-rs/tracing/blob/master/examples/examples/custom-error.rs#L54

If this is not done, then the trace generation for errors becomes broken in tests.

I am happy to submit a pull request next weekend

P.S. Thanks for the awesome crate, saves a lot of boilerplate!

**Comment by d-e-s-o** [comment]
Sure, happy to accept a pull request if it fits nicely into the existing design.

**Comment by d-e-s-o** [comment]
Given that the pull request was abandoned and you seem to be the only person asking for the feature, I'll close this issue. Feel free to reopen if you want to proceed on it.
