### ISSUE TITLE
Test env log adding `::f` to end of test name

### ISSUE THREAD

**Issue by casey** [d-e-s-o/test-env-log#5]
I think that `test_env_log::test` is modifying test names as reported by the runner. Here's a test annotated with `#[test]`:

```
     Running target/debug/deps/quwue-ace6fa7a6ba4cdb3

running 1 test
test run::tests::parse_message ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[Finished running. Exit status: 0]
```

And here's one with `test_env_log::test`:

```
     Running target/debug/deps/quwue-ace6fa7a6ba4cdb3

running 1 test
test run::tests::parse_message::f ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[Finished running. Exit status: 0]
```

Notice the extra `::f`.

**Comment by d-e-s-o** [comment]
That is required to allow for global imports. What exactly is the problem you are having?

**Comment by casey** [comment]
No particular problem, it's just unattractive and makes the test runner output harder to read.

**Comment by d-e-s-o** [comment]
I am not aware of another way to solve the problem, so I don't see how it can be removed. If you have a suggestion please let me know.

**Comment by casey** [comment]
Ahh, okay, I looked at the code and this is definitely a harder problem than I thought. I have no clever ideas to solve it 😅

**Comment by d-e-s-o** [comment]
FYI, I found a way to fix that peculiarity while keeping the desired behavior. Contained in `0.2.4`.

**Comment by casey** [comment]
NIce!
