### ISSUE TITLE
Support wrapping tokio::test

### ISSUE THREAD

**Issue by danielzfranklin** [d-e-s-o/test-env-log#7]
I expect this would be non-trivial, but it would be really nice to have this for async tests as a wrapper around tokio::test as well

**Comment by d-e-s-o** [comment]
Works already, see https://github.com/d-e-s-o/test-env-log/blob/813c3db3e66613d7be5a513d1c135fa2ec7f9c29/tests/mod.rs#L35.

I suppose it should be better advertised in the README.
